### ISSUE TITLE
DB から todo の一覧を表示するように変更

### ISSUE THREAD

**Issue by watagit** [watagit/react-go-todo-backend#10]
## 🎉 Goal
モックデータから表示している tod の一覧を DB から表示するように変更する．

## 📄 References
参考資料などを記載する．

## ✅ Tasks
必要な作業を記載する．
+ [x] Go で DB に接続する
+ [x] DB から 一覧が取得できる確認する
+ [x] `/api/v1/todos`にリクエストを送って一覧が取得できているか確認する

## 🆗 Closing Requirements
イシューを閉じる条件を記載する．
+ `/api/v1/todos`に GET リクエストを送って一覧が返ってくること．
